# Generated by Django 5.2.1 on 2025-06-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='emoji',
        ),
        migrations.AlterField(
            model_name='mood',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
