# Generated by Django 5.2.1 on 2025-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_remove_mood_emoji_alter_mood_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
