# Generated by Django 5.2.1 on 2025-06-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodpicker', '0001_initial'),
        ('moods', '0003_mood_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='moods.mood'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
